<template>
  <div class="modal fade" id="infoModal" tabindex="-1" aria-labelledby="infoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="infoModalLabel">About Smart City</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Smart city simulates the <strong><em>tokenization</em></strong> of energy produced in a green, decentralized way.</p>
          <p>In this simulator, users are able to buy solar farms to produce and supply energy to the grid.</p>
          <p>The solar farms come in three different sizes, and to simplify the calculations, we are going to assume that there are 5 peak sun hours everyday and this value keeps constant.</p>
          <table class="table table-sm table-light table-hover mb-0">
            <thead>
              <tr>
                <th scope="col">Size</th>
                <th scope="col">Price (NEAR)</th>
                <th scope="col">Panels (400W)</th>
                <th scope="col">Capacity (KWh per day)</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="element in farmsInfo">
                <th scope="row">{{element.size}}</th>
                <td>{{element.price}}</td>
                <td>{{element.panels}}</td>
                <td>{{element.capacity}}</td>
              </tr>
            </tbody>
          </table>
          <p>The main idea here is that the tokens will be paired with the KWs per hour that will be produced by the farms.</p>
          <p>To convert the KWh generated by the users' farms into tokens, users have to call the method <strong><em>withdraw</em></strong>.</p>
          <p>Finally, there is a method called <strong><em>redeem</em></strong> that users can call to convert their tokens into NEAR. The current value of each token is 0.0006 $NEAR.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        farmsInfo: [
          {
            size: "small",
            price: 100,
            panels: 80,
            capacity: 160
          },
          {
            size: "medium",
            price: 160,
            panels: 140,
            capacity: 280
          },
          {
            size: "small",
            price: 250,
            panels: 210,
            capacity: 420
          },
        ]
      };
    }
  };
</script>
